In [1]:
import torch

In [23]:
#a Tensor is the fundamental data structure used to store and manipulate data
#it is a multi-dimensional array of numbers.
a=torch.tensor([2,5,1])
b=torch.tensor([6,9,3])

sum=a+b
mal=a*b
minus=b-a

In [24]:
sum

tensor([ 8, 14,  4])

In [25]:
mal

tensor([12, 45,  3])

In [26]:
minus

tensor([4, 4, 2])

In [27]:
#for matrices
c=torch.tensor([[6,3,8],[2,7,1]])
d=torch.tensor([[0,1,5],[9,3,4],[2,6,1]])
mal1=torch.mm(c,d)
mal1

tensor([[43, 63, 50],
        [65, 29, 39]])

In [28]:
#for vectors to get dot product
e=torch.tensor([3,1,6,7,3])
f=torch.tensor([7,3,8,1,0])
sum1=torch.dot(e,f)
sum1

tensor(79)

In [29]:
g=torch.tensor([[4,2,6,7],[1,6,2,0],[2,7,8,4]])
g[1][3]

tensor(0)

In [30]:
m=torch.tensor([[7,7,7],[7,7,7],[7,7,7]],dtype=torch.float32)
v=torch.rand((3,3))
prod=torch.mm(m,v)
prod

tensor([[14.0701, 11.2458, 14.5551],
        [14.0701, 11.2458, 14.5551],
        [14.0701, 11.2458, 14.5551]])